AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Connectivitytype:
    Type: String
    Default: public
  CFNSubnet:
    Type: String
    Default: "subnet-84f326ee"
 
Resources:
  EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties: 
      AllocationId: !GetAtt 'EIP.AllocationId'
      ConnectivityType: !Ref Connectivitytype
      SubnetId: !Ref CFNSubnet
